name: Spack buildcache build

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main

env:
  SPACK_BACKTRACE: please
  SPACK_REF: b78c5175823910bc1f57e59a07d0b8c636e3f02d # develop-2024-12-22

jobs:
  rebuild:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

    - name: Install dependencies
      run: |
        sudo apt-get -q -y update
        sudo apt-get -q -y install \
          ccache cmake ninja-build python3 \
      
    - name: Setup Spack
      uses: spack/setup-spack@5792f7c7055c3707819380b5e3831d2be6e64b6c # 2024/12
      with:
        ref: ${{env.SPACK_REF}}
        buildcache: true
        color: true

    - name: Find compilers
      run: spack -e . compiler find --mixed-toolchain

    - name: Set buildcache
      run: |
        spack mirror add --unsigned upstream oci://ghcr.io/spack/github-actions-buildcache
        spack mirror add --unsigned celer-buildcache oci://ghcr.io/celeritas-project/spack-gha-buildcache

    - name: Concretize
      run: spack -e . -v concretize

    - name: Install
      run: |
        spack -e . env depfile -o Makefile
        make -Orecurse -j $(($(nproc) + 1)) SPACK_INSTALL_FLAGS=--no-check-signature

    - name: Push packages and update index
      run: |
        spack mirror set --push --oci-username ${{ github.actor }} --oci-password "${{ secrets.GITHUB_TOKEN }}" celer-buildcache
        spack -e . buildcache push -j $(($(nproc) + 1)) --base-image ubuntu:22.04 --update-index celer-buildcache
      if: ${{ !cancelled() }}
