name: Spack buildcache build

on:
  workflow_call:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      fresh:
        type: boolean
        description: Create a fresh buildcache
        default: false

env:
  SPACK_BACKTRACE: 1
  SPACK_REF: a91f96292c5d999463818365a3dfdabacdd3a31b # develop@2025-03-06

jobs:
  rebuild:
    runs-on: ubuntu-24.04 # NOTE: update 'push' below as well
    permissions:
      packages: write
    steps:
    - name: Checkout repo
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

    - name: Setup Spack
      uses: spack/setup-spack@5792f7c7055c3707819380b5e3831d2be6e64b6c # 2024/12
      with:
        ref: ${{env.SPACK_REF}}
        buildcache: true
        color: true

    - name: Patch spack # To be deleted; see associated github pulls
      working-directory: spack
      run: |
        for id in 49397 49511; do
          curl -LfsS "https://github.com/spack/spack/pull/${id}.diff" | patch -p1
        done

    - name: Find compilers
      run: spack -e . compiler find --mixed-toolchain

    - name: Set buildcache
      run: |
        spack mirror add --unsigned upstream oci://ghcr.io/spack/github-actions-buildcache
        spack mirror add --unsigned celer-buildcache oci://ghcr.io/celeritas-project/spack-gha-buildcache

    - name: Concretize (fresh)
      run: spack -e . -v concretize --fresh
      if: ${{ github.event.inputs.fresh == 'true' }}

    - name: Concretize (reuse)
      run: spack -e . -v concretize
      if: ${{ github.event.inputs.fresh == 'false' || github.event_name != 'workflow_dispatch' }}

    - name: Install
      run: |
        spack -e . env depfile -o Makefile
        make -Orecurse -j $(($(nproc) + 1)) SPACK_INSTALL_FLAGS=--no-check-signature

    - name: Push packages and update index
      env:
        GITHUB_USER: ${{github.actor}}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        spack mirror set --push --oci-username-variable GITHUB_USER --oci-password-variable GITHUB_TOKEN celer-buildcache
        spack -e . buildcache push -j $(($(nproc) + 1)) --base-image ubuntu:22.04 --update-index celer-buildcache
      if: ${{ !cancelled() }}

# vim: set nowrap tw=100:
